// Generated by CoffeeScript 1.12.4
var Type, type;

Type = require("Type");

type = Type("TimerMap");

type.defineValues(function() {
  return {
    _timers: Object.create(null)
  };
});

type.defineMethods({
  start: function(key, delay, callback) {
    this._timers[key] = setTimeout(callback, delay);
  },
  stop: function(key) {
    var id;
    if (id = this._timers[key]) {
      clearTimeout(id);
      delete this._timers[key];
    }
  }
});

module.exports = type.build();
